# custom_config.yaml 예시
task: detect
mode: train
model: yolov8n.yaml
data: data.yaml
epochs: 100
imgsz: 640
batch: 16

# 아래는 hyp (하이퍼파라미터)
# lr0: 0.01
# lrf: 0.1
# momentum: 0.937
# weight_decay: 0.0005
# warmup_epochs: 3.0
# warmup_momentum: 0.8
# warmup_bias_lr: 0.1
# box: 7.5
# cls: 0.5
# fliplr: 0.5
# mosaic: 1.0
# mixup: 0.2
